import type ModuleInstance from './main.js'

export type VariablesSchema = {
	playing_sounds: string[],

	img_autoloadbutton_sd_auto_load_button_base64: string,
	img_autoloadbutton_sd_auto_load_icon_base64: string,
	img_autoloadbutton_sd_auto_load_page_button_base64: string,
	img_autoloadbutton_sd_auto_load_page_icon_base64: string,
	img_autoloadbutton_sd_button_background_base64: string,
	img_censorbutton_sd_censor_icon_base64: string,
	img_censorbutton_sd_censor_image_base64: string,
	img_counter_icon_base64: string,
	img_counter_icon_2x_base64: string,
	img_counter_key_base64: string,
	img_counter_key_2x_base64: string,
	img_effectsbutton_sd_effects_off_base64: string,
	img_effectsbutton_sd_effects_on_base64: string,
	img_effectsbutton_sd_effects_toggle_icon_base64: string,
	img_hearself_sd_hear_self_off_base64: string,
	img_hearself_sd_hear_self_on_base64: string,
	img_playinganimation_sd_sound_playing_animation_1_base64: string,
	img_playinganimation_sd_sound_playing_animation_2_base64: string,
	img_playinganimation_sd_sound_playing_animation_3_base64: string,
	img_playinganimation_sd_sound_playing_animation_4_base64: string,
	img_playinganimation_sd_sound_playing_animation_5_base64: string,
	img_playsound_sd_ad_sound_button_base64: string,
	img_playsound_sd_add_sound_icon_base64: string,
	img_pushtotalk_mic_push_to_talk_icon_base64: string,
	img_pushtotalk_sd_mic_muted_base64: string,
	img_pushtotalk_sd_mic_open_base64: string,
	img_randomsoundbutton_sd_random_sound_button_icon_base64: string,
	img_randomsoundbutton_sd_random_sound_button_base64: string,
	img_randomsoundbutton_sd_random_sound_icon_base64: string,
	img_randomsoundbutton_sd_random_sound_mode_on_base64: string,
	img_randomsoundbutton_sd_random_sound_mode_base64: string,
	img_sfx_output_sd_sfx_output_icon_base64: string,
	img_sfx_output_sd_sfx_output_off_base64: string,
	img_sfx_output_sd_sfx_output_on_base64: string,
	img_soundsnap_sd_sound_snap_icon_base64: string,
	img_soundsnap_sd_soundsnap_on_base64: string,
	img_soundsnap_sd_soundsnap_base64: string,
	img_stop_stop_all_sounds_no_background_base64: string,
	img_stop_stop_all_sounds_base64: string,
	img_streampauser_sd_stream_icon_squared_base64: string,
	img_streampauser_sd_stream_icon_base64: string,
	img_streampauser_sd_stream_paused_base64: string,
	img_streampauser_sd_stream_played_base64: string,
	img_togglekeybinds_sd_keybinds_icon_2_base64: string,
	img_togglekeybinds_sd_keybinds_icon_base64: string,
	img_togglekeybinds_sd_keybinds_off_base64: string,
	img_togglekeybinds_sd_keybinds_on_base64: string,
	img_togglemic_sd_mic_icon_2_base64: string,
	img_togglemic_sd_mic_icon_base64: string,
	img_togglemic_sd_mic_off_base64: string,
	img_togglemic_sd_mic_on_base64: string,
	img_voicechanger_sd_voice_changer_button_base64: string,
	img_voicechanger_sd_voice_changer_icon_base64: string,
	img_whiteicons_sd_add_sound_icon_w_base64: string,
	img_whiteicons_sd_auto_load_button_icon_w_base64: string,
	img_whiteicons_sd_auto_load_page_icon_w_base64: string,
	img_whiteicons_sd_hear_self_icon_w_base64: string,
	img_whiteicons_sd_keybinds_icon_w_base64: string,
	img_whiteicons_sd_mic_icon_w_base64: string,
	img_whiteicons_sd_random_sound_button_icon_w_base64: string,
	img_whiteicons_sd_random_sound_mode_icon_w_base64: string,
	img_whiteicons_sd_stop_all_sound_icon_w_base64: string,
	img_whiteicons_sd_toggle_hear_self_icon_w_base64: string,
	img_whiteicons_sd_toggle_keybinds_icon_w_base64: string,
}

export function UpdateVariableDefinitions(self: ModuleInstance): void {
	self.setVariableDefinitions({
		playing_sounds: { name: 'Sounds paths currently playing' },

		img_autoloadbutton_sd_auto_load_button_base64: { name: "Image data: autoLoadButton SD Auto Load Button" },
		img_autoloadbutton_sd_auto_load_icon_base64: { name: "Image data: autoLoadButton SD Auto Load Icon" },
		img_autoloadbutton_sd_auto_load_page_button_base64: { name: "Image data: autoLoadButton SD Auto Load Page Button" },
		img_autoloadbutton_sd_auto_load_page_icon_base64: { name: "Image data: autoLoadButton SD Auto Load Page Icon" },
		img_autoloadbutton_sd_button_background_base64: { name: "Image data: autoLoadButton SD button Background" },
		img_censorbutton_sd_censor_icon_base64: { name: "Image data: censorButton sd Censor Icon" },
		img_censorbutton_sd_censor_image_base64: { name: "Image data: censorButton sd Censor Image" },
		img_counter_icon_base64: { name: "Image data: counter icon" },
		img_counter_icon_2x_base64: { name: "Image data: counter icon@2x" },
		img_counter_key_base64: { name: "Image data: counter key" },
		img_counter_key_2x_base64: { name: "Image data: counter key@2x" },
		img_effectsbutton_sd_effects_off_base64: { name: "Image data: effectsButton sd effects off" },
		img_effectsbutton_sd_effects_on_base64: { name: "Image data: effectsButton sd effects on" },
		img_effectsbutton_sd_effects_toggle_icon_base64: { name: "Image data: effectsButton sd effects toggle icon" },
		img_hearself_sd_hear_self_off_base64: { name: "Image data: hearSelf SD Hear Self Off" },
		img_hearself_sd_hear_self_on_base64: { name: "Image data: hearSelf SD Hear Self On" },
		img_playinganimation_sd_sound_playing_animation_1_base64: { name: "Image data: playingAnimation sd sound playing animation (1)" },
		img_playinganimation_sd_sound_playing_animation_2_base64: { name: "Image data: playingAnimation sd sound playing animation (2)" },
		img_playinganimation_sd_sound_playing_animation_3_base64: { name: "Image data: playingAnimation sd sound playing animation (3)" },
		img_playinganimation_sd_sound_playing_animation_4_base64: { name: "Image data: playingAnimation sd sound playing animation (4)" },
		img_playinganimation_sd_sound_playing_animation_5_base64: { name: "Image data: playingAnimation sd sound playing animation (5)" },
		img_playsound_sd_ad_sound_button_base64: { name: "Image data: playSound SD ad sound button" },
		img_playsound_sd_add_sound_icon_base64: { name: "Image data: playSound SD add sound icon" },
		img_pushtotalk_mic_push_to_talk_icon_base64: { name: "Image data: pushToTalk Mic Push To Talk Icon" },
		img_pushtotalk_sd_mic_muted_base64: { name: "Image data: pushToTalk SD Mic Muted" },
		img_pushtotalk_sd_mic_open_base64: { name: "Image data: pushToTalk SD Mic Open" },
		img_randomsoundbutton_sd_random_sound_button_icon_base64: { name: "Image data: randomSoundButton SD Random Sound Button Icon" },
		img_randomsoundbutton_sd_random_sound_button_base64: { name: "Image data: randomSoundButton SD Random Sound Button" },
		img_randomsoundbutton_sd_random_sound_icon_base64: { name: "Image data: randomSoundButton SD Random Sound Icon" },
		img_randomsoundbutton_sd_random_sound_mode_on_base64: { name: "Image data: randomSoundButton SD Random Sound Mode On" },
		img_randomsoundbutton_sd_random_sound_mode_base64: { name: "Image data: randomSoundButton SD Random Sound Mode" },
		img_sfx_output_sd_sfx_output_icon_base64: { name: "Image data: Sfx Output SD Sfx Output Icon" },
		img_sfx_output_sd_sfx_output_off_base64: { name: "Image data: Sfx Output SD Sfx Output Off" },
		img_sfx_output_sd_sfx_output_on_base64: { name: "Image data: Sfx Output SD Sfx Output On" },
		img_soundsnap_sd_sound_snap_icon_base64: { name: "Image data: SoundSnap SD Sound Snap Icon" },
		img_soundsnap_sd_soundsnap_on_base64: { name: "Image data: SoundSnap SD SoundSnap On" },
		img_soundsnap_sd_soundsnap_base64: { name: "Image data: SoundSnap SD SoundSnap" },
		img_stop_stop_all_sounds_no_background_base64: { name: "Image data: stop stop all sounds no background" },
		img_stop_stop_all_sounds_base64: { name: "Image data: stop stop all sounds" },
		img_streampauser_sd_stream_icon_squared_base64: { name: "Image data: streamPauser SD Stream Icon Squared" },
		img_streampauser_sd_stream_icon_base64: { name: "Image data: streamPauser SD Stream Icon" },
		img_streampauser_sd_stream_paused_base64: { name: "Image data: streamPauser SD Stream Paused" },
		img_streampauser_sd_stream_played_base64: { name: "Image data: streamPauser SD Stream Played" },
		img_togglekeybinds_sd_keybinds_icon_2_base64: { name: "Image data: toggleKeybinds SD Keybinds icon 2" },
		img_togglekeybinds_sd_keybinds_icon_base64: { name: "Image data: toggleKeybinds SD Keybinds icon" },
		img_togglekeybinds_sd_keybinds_off_base64: { name: "Image data: toggleKeybinds SD Keybinds off" },
		img_togglekeybinds_sd_keybinds_on_base64: { name: "Image data: toggleKeybinds SD Keybinds on" },
		img_togglemic_sd_mic_icon_2_base64: { name: "Image data: toggleMic SD mic icon 2" },
		img_togglemic_sd_mic_icon_base64: { name: "Image data: toggleMic SD mic icon" },
		img_togglemic_sd_mic_off_base64: { name: "Image data: toggleMic SD mic off" },
		img_togglemic_sd_mic_on_base64: { name: "Image data: toggleMic SD mic on" },
		img_voicechanger_sd_voice_changer_button_base64: { name: "Image data: voiceChanger sd Voice Changer Button" },
		img_voicechanger_sd_voice_changer_icon_base64: { name: "Image data: voiceChanger sd voice changer icon" },
		img_whiteicons_sd_add_sound_icon_w_base64: { name: "Image data: whiteIcons SD Add Sound Icon W" },
		img_whiteicons_sd_auto_load_button_icon_w_base64: { name: "Image data: whiteIcons SD Auto Load Button Icon W" },
		img_whiteicons_sd_auto_load_page_icon_w_base64: { name: "Image data: whiteIcons SD Auto Load Page Icon W" },
		img_whiteicons_sd_hear_self_icon_w_base64: { name: "Image data: whiteIcons SD Hear Self Icon W" },
		img_whiteicons_sd_keybinds_icon_w_base64: { name: "Image data: whiteIcons SD Keybinds Icon W" },
		img_whiteicons_sd_mic_icon_w_base64: { name: "Image data: whiteIcons SD Mic Icon W" },
		img_whiteicons_sd_random_sound_button_icon_w_base64: { name: "Image data: whiteIcons SD Random Sound Button Icon W" },
		img_whiteicons_sd_random_sound_mode_icon_w_base64: { name: "Image data: whiteIcons SD Random Sound Mode Icon W" },
		img_whiteicons_sd_stop_all_sound_icon_w_base64: { name: "Image data: whiteIcons SD Stop All Sound Icon W" },
		img_whiteicons_sd_toggle_hear_self_icon_w_base64: { name: "Image data: whiteIcons SD Toggle Hear Self Icon W" },
		img_whiteicons_sd_toggle_keybinds_icon_w_base64: { name: "Image data: whiteIcons SD Toggle Keybinds Icon W" },
	})
}
